# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('site_logo', models.FileField(upload_to='')),
                ('header_banner', models.FileField(upload_to='')),
            ],
        ),
    ]
