# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171030_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogoption',
            name='header_banner',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogoption',
            name='site_logo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
