# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171030_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogoption',
            name='favicon',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
