# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blogoption_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('featured_image', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
